<?xml version="1.0"?>
<robot name="PatoBombelSon" xmlns:xacro="http://ros.org/wiki/xacro">

	<!-- Wartości parametrow -->
	<xacro:property name="a2" value="0.5" />
	<xacro:property name="base_size" value="0.2" />
	<xacro:property name="gripper_size" value="0.01" />

	<!-- Stworzenie kolorow pokryc elementow -->
	<material name="blue">
		<color rgba="0 0 0.8 1"/>
	</material>

	<material name="black">
		<color rgba="0 0 0 1"/>
	</material>

	<material name="white">
		<color rgba="1 1 1 1"/>
	</material>

	<!-- Makro segmentMacro tworzace link - element robota -->
	<xacro:macro name="segmentMacro" params="name color xyz size">
		<link name="${name}">
			<visual>
				<geometry>
					<box size="${size}"/>
				</geometry>
				<material name="${color}"/>
				<origin xyz="${xyz}"/>
			</visual>
		</link>	
	</xacro:macro>
	
	<!-- Makro jointRevolute tworzące joint - tworzace ruchome polaczenie pomiedzy elementami robota -->
	<xacro:macro name="jointRevolute" params="parent child rpy xyz  axis_xyz limit_low limit_up">
		<joint name="${parent}_to_${child}_joint_continuous" type="revolute">
			<limit effort="1000.0" lower="${limit_low}" upper="${limit_up}" velocity="0.5"/>
			<axis  xyz="${axis_xyz}"/>
			<parent link="${parent}"/>
			<child link="${child}"/>
			<origin rpy="${rpy}" xyz="${xyz}"/>
		</joint>
	</xacro:macro>

	<!-- Wykorzystanie makra segmentMacro do stworzenia elementow robota -->
	<xacro:segmentMacro name="base_link" color="black" xyz="0 0 ${base_size/2}"     size="0.2 0.2 ${base_size}"/>
	<xacro:segmentMacro name="segment_1" color="white" xyz="0 0 ${0}"               size="0 0 0"/>
	<xacro:segmentMacro name="segment_2" color="blue"  xyz="${a2/2} 0 0 "           size="${a2} 0.1 0.1 "/>
	<xacro:segmentMacro name="gripper"   color="white" xyz="${gripper_size/2} 0 0 " size="${gripper_size} 0.1 0.1 "/>

	<!-- Wykorzystanie makra jointRevolute do stworzenia polaczen pomiedzy elementami robota -->
	<xacro:jointRevolute parent="base_link" child="segment_1" rpy="0 0 0"        xyz="0 0 ${base_size}" 
		axis_xyz="0 0 1" limit_low="-3.14" limit_up="3.14"/>
	<xacro:jointRevolute parent="segment_1" child="segment_2" rpy="${-pi/2} 0 0" xyz="0 0 0"            
		axis_xyz="0 0 1" limit_low="-1.54" limit_up="0"/>
	<xacro:jointRevolute parent="segment_2" child="gripper"   rpy="0 0 0"        xyz="${a2} 0 0"        
		axis_xyz="0 0 1" limit_low="0" limit_up="1.54"/>
</robot>

