<?xml version="1.0"?>
<robot name="PatoBombelDaughter" xmlns:xacro="http://ros.org/wiki/xacro">

	<!-- Wartości parametrow -->
	<xacro:property name="a2" value="0.3" />
	<xacro:property name="base_size" value="0.25" />
	<xacro:property name="gripper_size" value="0.2" />

	<!-- Stworzenie kolorow pokryc elementow -->
	<material name="blue">
		<color rgba="0 0 0.8 1"/>
	</material>

	<material name="black">
		<color rgba="0 0 0 1"/>
	</material>

	<material name="white">
		<color rgba="1 1 1 1"/>
	</material>

	<!-- Makro segmentMacro tworzace link - element robota -->
	<xacro:macro name="segmentMacro" params="name color xyz size">
		<link name="${name}">
			<visual>
				<geometry>
					<box size="${size}"/>
				</geometry>
				<material name="${color}"/>
				<origin xyz="${xyz}"/>
			</visual>
		</link>	
	</xacro:macro>
	
	<!-- Makro jointFixed tworzące joint - tworzace sztywne polaczenie pomiedzy elementami robota -->
	<xacro:macro name="jointFixed" params="parent child rpy xyz">
		<joint name="${parent}_to_${child}_joint_fixed" type="fixed">
			<parent link="${parent}"/>
			<child link="${child}"/>
			<origin rpy="${rpy}" xyz="${xyz}"/>
		</joint>
	</xacro:macro>

	<!-- Wykorzystanie makra segmentMacro do stworzenia elementow robota -->
	<xacro:segmentMacro name="base_link" color="black" xyz="0 0 ${base_size/2}"     size="0.2 0.2 ${base_size}"/>
	<xacro:segmentMacro name="segment_1" color="white" xyz="0 0 ${0}"               size="0 0 0"/>
	<xacro:segmentMacro name="segment_2" color="blue"  xyz="${a2/2} 0 0 "           size="${a2} 0.1 0.1 "/>
	<xacro:segmentMacro name="gripper"   color="white" xyz="${gripper_size/2} 0 0 " size="${gripper_size} 0.1 0.1 "/>

	<!-- Wykorzystanie makra jointFixed do stworzenia polaczen pomiedzy elementami robota -->
	<xacro:jointFixed parent="base_link" child="segment_1" rpy="0 0 0"        xyz="0 0 ${base_size}" />
	<xacro:jointFixed parent="segment_1" child="segment_2" rpy="${-pi/2} 0 0" xyz="0 0 0"            />
	<xacro:jointFixed parent="segment_2" child="gripper"   rpy="0 0 0"        xyz="${a2} 0 0"        />

</robot>
